### ISSUE TITLE
Cannot connect local playground to HSBNv1 blockchain service.

### ISSUE THREAD

**Issue by gormand** [hyperledger/composer#1184]
## Context

I have downloaded composer and HLF locally which all works fine, using docker. I also have an HSBN Beta v1 service which I have tried to connect the playground to unsuccessfully.

## Actual Behavior

I get errors such as:

0|composer | E0606 12:00:03.918329093      22 ssl_transport_security.c:611] Could not load any root certificate.
0|composer | E0606 12:00:03.918393517      22 ssl_transport_security.c:1348] Cannot load server root certificates.
0|composer | E0606 12:00:03.918425180      22 security_connector.c:837]   Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
0|composer | E0606 12:00:03.918445456      22 secure_channel_create.c:127] Failed to create secure subchannel for secure name ‘ldn1-zbc5a.2.secure.blockchain.ibm.com:33521’
0|composer | E0606 12:00:03.918464133      22 secure_channel_create.c:158] Failed to create subchannel arguments during subchannel creation.

## Steps to Reproduce

1. Download playground docker and start
2. Create HSBN v1 service
3. Create a channel
4. Use credentials from HSBN service to populate the playground profile
5. Click connect

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by davidkel** [comment]
Playground is still having having problems if you cut/paste certificate text from a json file containing /r/n. This appears to have to be preserved when writing out the connection.json for use otherwise tls connections fail. So for example playground is writing the certificate with just \n in the json file and this appears not to be valid.

**Comment by sstone1** [comment]
@davidkel you're best placed to test the fix for this - please can you take a look? It would be good to close this off. I assume we have some dodgy regex or code in playground somewhere. Jake is back in tomorrow so he can point you in the right direction.

**Comment by davidkel** [comment]
@sstone1 that's cool with me, I will take a look.

**Comment by davidkel** [comment]
fixed.

**Comment by vickygoel5988** [comment]
Hi,

I am still getting this issue while setting up https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-multi-org.

Please help.

[iid@iid first-network]$ composer network install --card PeerAdmin@byfn-network-org1 --archiveFile fis-kyc.bna 
⠹ Installing business network. This may take a minute...E0320 06:35:56.499831373   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.499865382   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.499890885   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.499902764   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:7051'
E0320 06:35:56.499911098   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.500278242   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.500288316   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.500301737   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.500310445   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:7051'
E0320 06:35:56.500318632   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.500755975   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.500767852   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.500781561   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.500790554   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:8051'
E0320 06:35:56.500798682   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.501151726   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.501161592   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.501174912   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.501183570   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:8051'
E0320 06:35:56.501191613   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.501619999   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.501631625   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.501645554   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.501654421   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:9051'
E0320 06:35:56.501662515   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.502014117   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.502023715   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.502036951   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.502045585   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:9051'
E0320 06:35:56.502053602   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.502430912   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.502440676   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.502453962   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.502462590   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:10051'
E0320 06:35:56.502470771   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.502864099   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.502875275   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.502888785   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.502897431   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:10051'
E0320 06:35:56.502905506   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
⠸ Installing business network. This may take a minute...E0320 06:35:56.679349987   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.679372426   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.679383602   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.679389560   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:7051'
E0320 06:35:56.679393846   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.679566493   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.679574382   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.679582508   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.679587615   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:7051'
E0320 06:35:56.679591903   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.679781723   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.679789988   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.679808254   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.679813196   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:8051'
E0320 06:35:56.679817453   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
E0320 06:35:56.679986146   26526 ssl_transport_security.cc:599] Could not load any root certificate.
E0320 06:35:56.679993807   26526 ssl_transport_security.cc:1400] Cannot load server root certificates.
E0320 06:35:56.680001722   26526 security_connector.cc:1025] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0320 06:35:56.680006573   26526 secure_channel_create.cc:111] Failed to create secure subchannel for secure name 'localhost:8051'
E0320 06:35:56.680011047   26526 secure_channel_create.cc:142] Failed to create subchannel arguments during subchannel creation.
✖ Installing business network. This may take a minute...
Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
Response from attempted peer comms was an error: Error: REQUEST_TIMEOUT
Command failed

Thanks,
Vicky
