### ISSUE TITLE
Version update script does not update the peer dependencies versions 

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#3954]
`composer-common` is marked as a peer dependency of things such as the `composer-wallet-filesystem`

This means that issues such as 

```
npm WARN composer-wallet-filesystem@0.19.4 requires a peer of composer-common@0.19.3 but none is installed. You must install peer dependencies yourself.
npm WARN composer-wallet-inmemory@0.19.4 requires a peer of composer-common@0.19.3 but none is installed. You must install peer dependencies yourself.

```

Can occur...

**Comment by mbwhite** [comment]
Resolved in #https://github.com/hyperledger/composer/pull/3955

**Comment by fefifofums** [comment]
I still get this error after running npm commands form https://hyperledger.github.io/composer/unstable/installing/development-tools.html.  

ex - npm install -g generator-hyperledger-composer

returns -
npm WARN composer-wallet-filesystem@0.19.4 requires a peer of composer-common@0.19.3 but none is installed. You must install peer dependencies yourself.
npm WARN composer-wallet-inmemory@0.19.4 requires a peer of composer-common@0.19.3 but none is installed. You must install peer dependencies yourself.


How can I resolve this issue?  I am running ubuntu 16.04.  Please let me know if you need more details.

**Comment by zasamen** [comment]
I'm getting that:
`npm ERR! peer dep missing: composer-common@0.19.3, required by composer-wallet-filesystem@0.19.4`
what should i do to resolve it?
i've got it after update. [https://hyperledger.github.io/composer/unstable/installing/development-tools.html](link of doc)

**Comment by AqeelKazmi** [comment]
In my case when i run 
sudo npm install -g composer-cli
on aws instance, it shows me these warnings --->

npm WARN composer-wallet-filesystem@0.19.4 requires a peer of composer-common@0.19.3 but none is installed. You must install peer dependencies yourself.

npm WARN composer-wallet-inmemory@0.19.4 requires a peer of composer-common@0.19.3 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/composer-cli/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

After these warnings also shows-->
+ composer-cli@0.19.4
updated 1 package in 9.568s


But when i check either it is installed or not , it displays composer-cli not found...
& Due to this i am unable to install 
composer-rest-server
generator-hyperledger-composer
yo


Kindly guide me as i am using fabric template of aws instance
