### ISSUE TITLE
Opaque error message when using POJOs with AssetRegistry.add & other composer-runtime functions

### ISSUE THREAD

**Issue by pospi** [hyperledger/composer#647]
## Context

Chaincode logic crashes on `getAssetRegistry()` when the asset class extends from an abstract base class.

## Expected Behavior

The asset registry should be returned for creating & managing assets.

## Actual Behavior

Peer logs `13:48:51.680 [chaincode] processStream -> ERRO 5b0 Got error: TypeError: 'getFullyQualifiedIdentifier' is not a function` and the transaction is rejected.

## Steps to Reproduce

Since I can't upload attachments to github, here are the files in my test network module:

`package.json`:
```
{
  "name": "net.test.modelinheritance",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "WTFPL"
}
```

`models/org.network.core.cto`:
```
namespace org.network.core

abstract asset BaseAsset identified by id {
  o String id
  o DateTime createdOn
  --> BaseMember invoker
  --> BaseAsset parent optional
}

abstract participant BaseMember identified by id {
  o String id
  o DateTime createdOn
  --> BaseMember invoker
}

abstract transaction BaseTransaction identified by id {
  o String id
  o String invoker
}
```

`models/org.network.test.cto`:
```
namespace org.network.test

import org.network.core.BaseAsset
import org.network.core.BaseMember
import org.network.core.BaseTransaction

asset TestAsset extends BaseAsset {
  o String testField
}

participant TestMember extends BaseMember {
  o String testField
}

transaction TestTransaction extends BaseTransaction {
  o String testField
}
```

`lib/logic.js`:
```
function onTestTransaction(testTransaction) {
    return getAssetRegistry('org.network.test.TestAsset')
        .then(function(AR) {
            return AR.add({
                id: 'assetfrom_' + testTransaction.id,
                createdOn: new Date(),
                invoker: 'someparticipantid',
                testField: 'test',
            });
        });
}
```

## Context

Since this isn't working for us yet we're currently duplicating all our base model fields instead of using the inheritance feature, which isn't maintainable long-term.

## Your Environment

* Version used: `0.5.9`
* Environment name and version: Ubuntu 16.40, nodejs 6.9.1, fabric-baseimage x86_64-0.3.0

**Comment by pospi** [comment]
I've been building an integration test running with `composer-connector-embedded` so now I've managed to get a stack trace as well :D

```
[TypeError: resource.getFullyQualifiedIdentifier is not a function]
  AccessController.check (node_modules/composer-runtime/lib/accesscontroller.js:71:36)
  Registry.add (node_modules/composer-runtime/lib/registry.js:147:31)
  AssetRegistry.add (node_modules/composer-runtime/lib/api/assetregistry.js:195:29)
  callee$1$0$ (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9278:14)
  tryCatch (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9350:40)
  GeneratorFunctionPrototype.invoke [as _invoke] (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9624:22)
  GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9383:21)
  c (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:7:40)
```

**Comment by rodders1991** [comment]
This doesn't seem to limited to inherent models, getting the same error when trying to add the following asset via a transaction:

`models/org.network.diamond`
```
namespace org.network.diamond

asset Report identified by id {
  o ReportType report_type
  o String id  
  o DateTime createdOn
  o String invoker
  o Double carat_weight
  o String carat_measurements
  o ColourGrade colour_grade
}

transaction CreateReport identified by id {
  o String id
  o ReportDTO report
  o String invoker
}
concept ReportDTO {
  o ReportType report_type
  o String id 
  o String invoker
  o Double carat_weight
  o String carat_measurements
  o ColourGrade colour_grade
}
```

All special type (e.g ColourGrade) are enums:

`lib/logic.js`

```
function onCreateReport(createReport) {
    return getAssetRegistry('org.network.diamond.Report')
        .then(function(AR) {
            return AR.add({
                id: 'assetfrom_' + createReport.id,
                createdOn: new Date(),
                invoker: createReport.invoker,
                carat_weight: createReport.report.carat_weight,
                carat_measurements: createReport.report.carat_measurements,
                colour_grade: createReport.report.colour_grade,
                report_type:  createReport.report.report_type,
            });
        });
}

```

Error:

```
  [TypeError: resource.getFullyQualifiedIdentifier is not a function]

  AccessController.check (node_modules/composer-runtime/lib/accesscontroller.js:71:36)
  Registry.add (node_modules/composer-runtime/lib/registry.js:147:31)
  AssetRegistry.add (node_modules/composer-runtime/lib/api/assetregistry.js:195:29)
  callee$1$0$ (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9321:14)
  tryCatch (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9393:40)
  GeneratorFunctionPrototype.invoke [as _invoke] (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9667:22)
  GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:9426:21)
  c (eval at <anonymous> (node_modules/composer-runtime/lib/jstransactionexecutor.js:170:20), <anonymous>:7:40)
```

**Comment by davidkel** [comment]
Looking at the docs at
https://fabric-composer.github.io/jsdoc/module-composer-runtime.AssetRegistry.html#add__anchor
would suggest that you cannot add POJOs to an asset registry but need to create asset instances using a factory.
The code should protect against passing a type of object in that isn't expected and should reject it with a helpful error message.

**Comment by pospi** [comment]
Thanks David, this does seem to have been the error and we've fixed things by wrapping the object in a factory call. I've changed the issue title accordingly as I believe all we really need is a better error message.

**Comment by EllisHenderson** [comment]
Tried to recreate this issue by adding a POJO to an asset registry without using a factory and was met with an error message stating that a resource was expected. Looks like this issue has already been fixed.

**Comment by davidkel** [comment]
Just tried this using the latest playground using the web runtime and got the error
`TypeError: e.getFullyQualifiedIdentifier is not a function`
So not convinced this is fixed or at least not fixed for the web runtime.

**Comment by kletkeman** [comment]
Definitely not fixed in v0.13.2 ... but I'm so glad it is searchable to this issue :-)
